---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Elasticsearch.
  package:
    name: elasticsearch
    state: "{{ elasticsearch_package_state }}"
  tags:
    - install

- name: Install Pip
  yum:
    name: python-pip

- name: Install pexpect
  pip:
    name: pexpect
  become: yes
  