---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ${VAGRANT_DEFAULT_BOX:-generic/rhel7}
    groups:
      - elasticsearch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: converge.yml
    cleanup: cleanup.yml
  inventory:
    group_vars:
      elasticsearch:
        ca_crt: ../resources/ca/ca.crt
    host_vars:
      instance:
        server_crt: ../resources/{{ ansible_hostname }}/{{ ansible_hostname }}.crt
        server_key: ../resources/{{ ansible_hostname }}/{{ ansible_hostname }}.key
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
